### ISSUE TITLE
September 28th code review

### ISSUE THREAD

**Issue by SunnySparks** [mike2611/todo-list-mv#8]
Great job at implementing the drag and drop feature!

Another way you can make your addition to the list more intuitive is by adding the function to hit enter after you finished typing the description, this one worked very well for me: 

`textField.addEventListener('keyup', (event) => {
if (event.keyCode === 13 && htmlInput.value !== '') {
fillTaskList(myList);textField.value = '';
}
});
`

**Comment by dicodiaz** [comment]
### Hello @mike2611, this is an awesome project. You're doing a great job!

Features I liked a lot: 
- The "click anywhere else" way to enter an edit.
- The drag & drop.

Additional features you might want to implement:
- Drag & drop functionality for mobile. For this, you can use ```touchstart```, ```touchend``` and ```touchmove``` event listeners. Also, please have in mind that the ```y``` position catching for mobile is a little different. You could catch it for desktop or mobile in a single liner like this:
```const y = e.clientY || e.touches[0].clientY;``` where ```e``` is the event variable.
- The same "hit enter" way to enter edits in addition to new tasks as recommended by @SunnySparks.

I believe both recommendations would improve UX.

The rest of the code you implemented is working great. Keen up the good work! 😄

**Comment by mike2611** [comment]
Thank you for your great recommendations, I already applied the required changes. I'm closing the issue.
